# AppViewUtilits document generator jazzy settings

copyright: Copyright 2021 moslienko
author: Pavel Moslienko
xcodebuild_arguments: [-target, AppViewUtilits-iOS]
clean: true
output: ./Documentation
